from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

btnMainRuss = KeyboardButton("Главное меню")
btnMainTjk = KeyboardButton("Менюи асосӣ️")
btnMainEng = KeyboardButton("Main menu")
btnMainUzb = KeyboardButton("Asosiy menyu")

# --- Main Menu ---
btnPlaceRuss = KeyboardButton("Посетить популярные места 📍")
btnPlaceEng = KeyboardButton("Visit popular places 📍")
btnPlaceTjk = KeyboardButton("Ба ҷойҳои машҳур сафар кунед 📍")
btnPlaceUzb = KeyboardButton("Mashhur joylarga tashrif buyuring 📍")
btnFoodEng = KeyboardButton("National food 🍗")
btnFoodRuss = KeyboardButton("Национальная еда 🍗")
btnFoodTjk = KeyboardButton("Хӯроки миллӣ 🍗")
btnFoodUzb = KeyboardButton("Milliy taomlar 🍗")
btnLangRuss = KeyboardButton("Изменить язык 🇹🇯🇺🇸🇺🇿")
btnLangEng = KeyboardButton("Change the language 🇷🇺🇹🇯🇺🇿")
btnLangTjk = KeyboardButton("Забонро иваз кунед 🇺🇸🇷🇺🇺🇿")
btnLangUzb = KeyboardButton("Tilni o'zgartirish 🇹🇯🇺🇸🇷🇺")
btnHelpRuss = KeyboardButton("Помочь проекту 💵")
btnHelpEng = KeyboardButton("Help to project 💵")
btnHelpTjk = KeyboardButton("Лойиҳага ёрдам беринг 💵")
btnHelpUzb = KeyboardButton("Loyihaga yordam bering 💵")
btnNewsRuss = KeyboardButton("Новости 📰")
btnNewsEng = KeyboardButton("News 📰")
btnNewsTjk = KeyboardButton("Ахбор 📰")
btnNewsUzb = KeyboardButton("Yangiliklar 📰")
btnOthRuss = KeyboardButton("Другое")
btnOthEng = KeyboardButton("Other")
btnOthTjk = KeyboardButton("Дигар")
btnOthUzb = KeyboardButton("Boshqa")
mainMenuRuss = ReplyKeyboardMarkup(resize_keyboard=True).add(btnPlaceRuss, btnFoodRuss, btnLangRuss, btnHelpRuss, btnNewsRuss, btnOthRuss)
mainMenuTjk = ReplyKeyboardMarkup(resize_keyboard=True).add(btnPlaceTjk, btnFoodTjk, btnLangTjk, btnHelpTjk, btnNewsTjk, btnOthTjk)
mainMenuEng = ReplyKeyboardMarkup(resize_keyboard=True).add(btnPlaceEng, btnFoodEng, btnLangEng, btnHelpEng, btnNewsEng, btnOthEng)
mainMenuUzb = ReplyKeyboardMarkup(resize_keyboard=True).add(btnPlaceUzb, btnFoodUzb, btnLangUzb, btnHelpUzb, btnNewsUzb, btnOthUzb)

# --- Places ---
btnPmkRuss = KeyboardButton("Популярные достопремечательности 🏰")
btnPmkEng = KeyboardButton("Popular Attractions 🏰")
btnPmkTjk = KeyboardButton("Ҷойҳои машҳур 🏰")
btnPmkUzb = KeyboardButton("Mashhur diqqatga sazovor joylar 🏰")
btnProRuss = KeyboardButton("Прогулка 🚶")
btnProEng = KeyboardButton("Walk 🚶")
btnProTjk = KeyboardButton("Пиёда рафтан 🚶")
btnProUzb = KeyboardButton("Yurish 🚶")
btnPokRuss = KeyboardButton("Покупки 🛍 ")
btnPokEng = KeyboardButton("Shopping 🛍")
btnPokTjk = KeyboardButton("Харид 🛍")
btnPokUzb = KeyboardButton("Xarid qilish 🛍")
placesRuss = ReplyKeyboardMarkup(resize_keyboard=True).add(btnPmkRuss, btnProRuss, btnPokRuss, btnMainRuss)
placesEng = ReplyKeyboardMarkup(resize_keyboard=True).add(btnPmkEng, btnProEng, btnPokEng, btnMainEng)
placesTjk = ReplyKeyboardMarkup(resize_keyboard=True).add(btnPmkTjk, btnProTjk, btnPokTjk, btnMainTjk)
placesUzb = ReplyKeyboardMarkup(resize_keyboard=True).add(btnPmkUzb, btnProUzb, btnPokUzb, btnMainUzb)

# --- City ---
btnDushRuss = KeyboardButton("Душанбе 🏙")
btnHudRuss = KeyboardButton("Худжанд 🏙")
btnKulRuss = KeyboardButton("Куляб 🏙")
btnDushEng = KeyboardButton("Dushanbe 🌃")
btnHudEng = KeyboardButton("Khujand 🌃")
btnKulEng = KeyboardButton("Kulob 🌃")
btnDushTjk = KeyboardButton("Душанбе 🌆")
btnHudTjk = KeyboardButton("Хучанд 🌆")
btnKulTjk = KeyboardButton("Кулоб 🌆")
btnDushUzb = KeyboardButton("Dushanbe 🏙")
btnHudUzb = KeyboardButton("Xo'jand 🏙")
btnKulUzb = KeyboardButton("Koʻlob 🏙")
cityRuss = ReplyKeyboardMarkup(resize_keyboard=True).add(btnDushRuss, btnHudRuss, btnKulRuss, btnMainRuss)
cityEng = ReplyKeyboardMarkup(resize_keyboard=True).add(btnDushEng, btnHudEng, btnKulEng, btnMainEng)
cityTjk = ReplyKeyboardMarkup(resize_keyboard=True).add(btnDushTjk, btnHudTjk, btnKulTjk, btnMainTjk)
cityUzb = ReplyKeyboardMarkup(resize_keyboard=True).add(btnDushUzb, btnHudUzb, btnKulUzb, btnMainUzb)

# --- Language Menu ---
btnRuss = KeyboardButton("Русский 🇷🇺")
btnEng = KeyboardButton("English 🇺🇸")
btnTjk = KeyboardButton("Тоҷикӣ 🇹🇯")
btnUzb = KeyboardButton("O'zbek 🇺🇿")
langMenu = ReplyKeyboardMarkup(resize_keyboard=True).add(btnRuss, btnEng, btnTjk, btnUzb)

# --- Restoraunt Menu ---
btnRestorauntEng = KeyboardButton("Where I can eat this food? 🍗")
btnRestorauntRuss = KeyboardButton("Где я смогу поесть эту еду? 🍗")
btnRestorauntTjk = KeyboardButton("Дар куҷо ман метавонам ин хӯрокро бихӯрам? 🍗")
btnRestorauntUzb = KeyboardButton("Bu taomni qayerda yeyishim mumkin? 🍗")
restoMenuTjk = ReplyKeyboardMarkup(resize_keyboard=True).add(btnRestorauntTjk, btnMainTjk)
restoMenuRuss = ReplyKeyboardMarkup(resize_keyboard=True).add(btnRestorauntRuss, btnMainRuss)
restoMenuEng = ReplyKeyboardMarkup(resize_keyboard=True).add(btnRestorauntEng, btnMainEng)
restoMenuUzb = ReplyKeyboardMarkup(resize_keyboard=True).add(btnRestorauntUzb, btnMainUzb)

# --- Taxi menu ---
btnTaxiRuss = KeyboardButton("Как мне добраться туда?")
btnTaxiEng = KeyboardButton("How can I get there?")
btnTaxiTjk = KeyboardButton("Чӣ тавр ман метавонам ба он ҷо расам?")
btnTaxiUzb = KeyboardButton("Qanday qilib u erga borishim mumkin?")
taxiMenuRuss = ReplyKeyboardMarkup(resize_keyboard=True).add(btnTaxiRuss, btnMainRuss)
taxiMenuTjk = ReplyKeyboardMarkup(resize_keyboard=True).add(btnTaxiTjk, btnMainTjk)
taxiMenuEng = ReplyKeyboardMarkup(resize_keyboard=True).add(btnTaxiEng, btnMainEng)
taxiMenuUzb = ReplyKeyboardMarkup(resize_keyboard=True).add(btnTaxiUzb, btnMainUzb)

# --- Support menu ---
btnSupportRuss = KeyboardButton("Связатся с тех.поддержкой 👨🏻‍💻")
btnSupportEng = KeyboardButton("Contact technical support 👨🏻‍💻")
btnSupportTjk = KeyboardButton("Бо дастгирии техникӣ тамос гиред 👨🏻‍💻")
btnSupportUzb = KeyboardButton("Texnik yordam xizmatiga murojaat qiling 👨🏻‍💻")
btnInforRuss = KeyboardButton("Информация ℹ️")
btnInforEng = KeyboardButton("Information ℹ️")
btnInforTjk = KeyboardButton("Маълумот ℹ️")
btnInforUzb = KeyboardButton("ma`lumot ℹ️")
inforMenuRuss = ReplyKeyboardMarkup(resize_keyboard=True).add(btnSupportRuss, btnInforRuss)
inforMenuEng = ReplyKeyboardMarkup(resize_keyboard=True).add(btnSupportEng, btnInforEng)
inforMenuTjk = ReplyKeyboardMarkup(resize_keyboard=True).add(btnSupportTjk, btnInforTjk)
inforMenuUzb = ReplyKeyboardMarkup(resize_keyboard=True).add(btnSupportUzb, btnInforUzb)

# --- Other Menu ---
btnInfoRuss = KeyboardButton("Информация о боте ℹ️")
btnInfoTjk = KeyboardButton("Маълумоти бот ℹ️")
btnInfoUzb = KeyboardButton("Bot haqida ma'lumot ℹ️")
btnInfoEng = KeyboardButton("Information about bot ℹ️")
btnSosRuss = KeyboardButton("Экстренные службы ⛑")
btnSosEng = KeyboardButton("Emergency services ⛑")
btnSosTjk = KeyboardButton("Хадамоти фавқулодда ⛑")
btnSosUzb = KeyboardButton("Favqulodda xizmatlar ⛑")

otherMenuRuss = ReplyKeyboardMarkup(resize_keyboard=True).add(btnInfoRuss, btnSosRuss, btnMainRuss)
otherMenuEng = ReplyKeyboardMarkup(resize_keyboard=True).add(btnInfoEng, btnSosEng, btnMainEng)
otherMenuTjk = ReplyKeyboardMarkup(resize_keyboard=True).add(btnInfoTjk, btnSosTjk, btnMainTjk)
otherMenuUzb = ReplyKeyboardMarkup(resize_keyboard=True).add(btnInfoUzb, btnSosUzb, btnMainUzb)
